### ISSUE TITLE
Encountered some problems with experimental reproduction

### ISSUE THREAD

**Issue by Corey01327** [nsg-ethz/Chameleon#1]
I am very interested in the Chameleon architecture, but I encountered some problems during the replication experiment:
1. How was Figure 8 drawn? After following the instructions, the graph I obtained is a straight line: Docker run - it - v $(pwd)/results:/chameleon/results chameleon python3 analysis/plot_ Specification_ Complexy.py

![Figure 8](https://github.com/nsg-ethz/Chameleon/assets/115163600/1a5bb580-7301-428f-97f7-4fc082a33550)

2. How were Figures 10, 11, and 12 obtained? Executing the relevant commands still did not yield the expected results.

**Comment by Corey01327** [comment]
Thanks,It has been found that Figure 8 is the result of analyzing dataset 2.

**Comment by tiborschneider** [comment]
Seems like there is a typo in the readme. Figure 8 requires dataset 2 (iterating over different specifications). I updated the documentation accordingly.

I am looking into the result for the other figures.

**Edit**: Most of the figure numbers were inaccurate (due to reshuffling of figures for the camera-ready). They should now be correct.

**Comment by tiborschneider** [comment]
I am closing this issue now. Please re-open if you are still unable to reconstruct the plots.
